import { existsSync } from 'node:fs';
import postgres from 'postgres';

if (existsSync('../../.env')) {
  process.loadEnvFile('../../.env');
}

const dryRun = process.argv.includes('--dry-run');
const rollback = process.argv.includes('--rollback');
const validate = process.argv.includes('--validate');

const DEFAULT_VOICEMAIL_INTRO_MESSAGE =
  'The line is ringing. If nobody answers, you can leave a voicemail after the peep.';
const DEFAULT_VOICEMAIL_POST_BEEP_MESSAGE =
  'Leave your message now. Your next DM here will be delivered as voicemail.';

function sqlString(value: string): string {
  return value.replace(/'/g, "''");
}

/**
 * Statements ordered so every FK target exists before its referent and so all CHECK
 * constraints are added with `NOT VALID` — this avoids a table-wide scan + AccessExclusiveLock
 * on production tables that may have pre-migration rows that violate the new shape.
 *
 * After the migration applies the `NOT VALID` constraints, the operator can run
 * `pnpm --filter @hansard/db migrate:phones -- --validate` (or hand-run
 * `ALTER TABLE ... VALIDATE CONSTRAINT ...`) once they've cleaned up offending rows.
 */
const statements: string[] = [
  // gen_random_uuid() is in core on PG13+, pgcrypto on older versions. Idempotent guard.
  `CREATE EXTENSION IF NOT EXISTS pgcrypto;`,

  // === phone_numbers ===
  // `number_normalized` uniqueness is enforced on the **active** subset only (see partial
  // index below). New CREATE TABLE installs do not get a column-level UNIQUE here; legacy
  // deployments that had one get it dropped in the DO block immediately after.
  `CREATE TABLE IF NOT EXISTS "phone_numbers" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "player_id" uuid NOT NULL REFERENCES "players"("id"),
    "number_raw" varchar(32) NOT NULL,
    "number_normalized" varchar(32) NOT NULL,
    "label" varchar(64),
    "cached_character_name" varchar(128),
    "pseudonym" varchar(128),
    "voicemail_enabled" boolean NOT NULL DEFAULT true,
    "voicemail_intro_message" text DEFAULT '${sqlString(DEFAULT_VOICEMAIL_INTRO_MESSAGE)}',
    "voicemail_post_beep_message" text DEFAULT '${sqlString(DEFAULT_VOICEMAIL_POST_BEEP_MESSAGE)}',
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "deactivated_at" timestamptz
  );`,
  `ALTER TABLE "phone_numbers" ADD COLUMN IF NOT EXISTS "pseudonym" varchar(128);`,
  `ALTER TABLE "phone_numbers" ADD COLUMN IF NOT EXISTS "voicemail_enabled" boolean NOT NULL DEFAULT true;`,
  `ALTER TABLE "phone_numbers" ADD COLUMN IF NOT EXISTS "voicemail_intro_message" text;`,
  `ALTER TABLE "phone_numbers" ADD COLUMN IF NOT EXISTS "voicemail_post_beep_message" text;`,
  `ALTER TABLE "phone_numbers" ALTER COLUMN "voicemail_enabled" SET DEFAULT true;`,
  `ALTER TABLE "phone_numbers" ALTER COLUMN "voicemail_intro_message" SET DEFAULT '${sqlString(DEFAULT_VOICEMAIL_INTRO_MESSAGE)}';`,
  `ALTER TABLE "phone_numbers" ALTER COLUMN "voicemail_post_beep_message" SET DEFAULT '${sqlString(DEFAULT_VOICEMAIL_POST_BEEP_MESSAGE)}';`,
  `UPDATE "phone_numbers"
    SET "voicemail_enabled" = true,
        "voicemail_intro_message" = COALESCE("voicemail_intro_message", '${sqlString(DEFAULT_VOICEMAIL_INTRO_MESSAGE)}'),
        "voicemail_post_beep_message" = COALESCE("voicemail_post_beep_message", '${sqlString(DEFAULT_VOICEMAIL_POST_BEEP_MESSAGE)}')
    WHERE "is_active" = true
      AND ("voicemail_enabled" = false
        OR "voicemail_intro_message" IS NULL
        OR "voicemail_post_beep_message" IS NULL);`,
  // Drop any legacy column-level UNIQUE constraint on number_normalized so retired numbers
  // can be re-registered. The constraint name is auto-generated by PG (commonly
  // `phone_numbers_number_normalized_key`); look it up by column rather than guessing.
  `DO $$
  DECLARE
    uniq_name text;
  BEGIN
    SELECT c.conname INTO uniq_name
    FROM pg_constraint c
    WHERE c.conrelid = '"phone_numbers"'::regclass
      AND c.contype = 'u'
      AND c.conkey = ARRAY[(
        SELECT a.attnum FROM pg_attribute a
        WHERE a.attrelid = '"phone_numbers"'::regclass
          AND a.attname = 'number_normalized'
      )::int2];
    IF uniq_name IS NOT NULL THEN
      EXECUTE format('ALTER TABLE "phone_numbers" DROP CONSTRAINT %I', uniq_name);
    END IF;
  END $$;`,
  // Some legacy deployments may have a standalone unique index rather than a unique
  // constraint. Drop only whole-table unique indexes that cover exactly number_normalized;
  // keep the new partial active-only index (indpred IS NOT NULL) and unrelated indexes.
  `DO $$
  DECLARE
    idx record;
  BEGIN
    FOR idx IN
      SELECT ns.nspname AS schema_name, cls.relname AS index_name
      FROM pg_index i
      JOIN pg_class cls ON cls.oid = i.indexrelid
      JOIN pg_namespace ns ON ns.oid = cls.relnamespace
      WHERE i.indrelid = '"phone_numbers"'::regclass
        AND i.indisunique = true
        AND i.indisprimary = false
        AND i.indexprs IS NULL
        AND i.indpred IS NULL
        AND i.indkey = (
          SELECT a.attnum::text::int2vector
          FROM pg_attribute a
          WHERE a.attrelid = '"phone_numbers"'::regclass
            AND a.attname = 'number_normalized'
        )
    LOOP
      EXECUTE format('DROP INDEX IF EXISTS %I.%I', idx.schema_name, idx.index_name);
    END LOOP;
  END $$;`,
  // CHECK added with NOT VALID so pre-existing violating rows don't abort the migration.
  // The CHECK still enforces on every future insert/update; legacy rows can be reconciled later.
  `DO $$ BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'phone_numbers_normalized_shape'
        AND conrelid = '"phone_numbers"'::regclass
    )
    THEN ALTER TABLE "phone_numbers" ADD CONSTRAINT "phone_numbers_normalized_shape"
      CHECK (number_normalized ~ '^\\+?[0-9]{3,20}$') NOT VALID;
    END IF;
  END $$;`,
  `CREATE INDEX IF NOT EXISTS "phone_numbers_player_idx" ON "phone_numbers" ("player_id");`,
  // Active-only uniqueness: a number is unique among live registrations, but retired rows
  // (`is_active=false`) don't block a future re-registration of the same digits.
  `CREATE UNIQUE INDEX IF NOT EXISTS "phone_numbers_active_normalized_unique"
    ON "phone_numbers" ("number_normalized") WHERE is_active = true;`,

  // === phone_calls ===
  `CREATE TABLE IF NOT EXISTS "phone_calls" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "caller_number_id" uuid NOT NULL REFERENCES "phone_numbers"("id"),
    "recipient_number_id" uuid NOT NULL REFERENCES "phone_numbers"("id"),
    "caller_player_id" uuid NOT NULL REFERENCES "players"("id"),
    "recipient_player_id" uuid NOT NULL REFERENCES "players"("id"),
    "status" varchar(16) NOT NULL DEFAULT 'ringing',
    "ended_reason" varchar(80),
    "ring_discord_message_id" varchar(20),
    "staff_thread_id" varchar(20),
    "voicemail_enabled" boolean NOT NULL DEFAULT false,
    "voicemail_intro_message" text,
    "voicemail_post_beep_message" text,
    "voicemail_peep_claimed_at" timestamptz,
    "voicemail_beeped_at" timestamptz,
    "ring_expires_at" timestamptz,
    "started_at" timestamptz NOT NULL DEFAULT now(),
    "answered_at" timestamptz,
    "ended_at" timestamptz
  );`,
  `ALTER TABLE "phone_calls" ADD COLUMN IF NOT EXISTS "voicemail_enabled" boolean NOT NULL DEFAULT false;`,
  `ALTER TABLE "phone_calls" ADD COLUMN IF NOT EXISTS "voicemail_intro_message" text;`,
  `ALTER TABLE "phone_calls" ADD COLUMN IF NOT EXISTS "voicemail_post_beep_message" text;`,
  `ALTER TABLE "phone_calls" ADD COLUMN IF NOT EXISTS "voicemail_peep_claimed_at" timestamptz;`,
  `ALTER TABLE "phone_calls" ADD COLUMN IF NOT EXISTS "voicemail_beeped_at" timestamptz;`,
  `DO $$
  DECLARE
    cur_def text;
  BEGIN
    SELECT pg_get_constraintdef(c.oid) INTO cur_def
    FROM pg_constraint c
    WHERE c.conname = 'phone_calls_status_check'
      AND c.conrelid = '"phone_calls"'::regclass;
    IF cur_def IS NULL THEN
      ALTER TABLE "phone_calls" ADD CONSTRAINT "phone_calls_status_check"
        CHECK (status IN ('ringing','active','voicemail','ended','declined','missed','cancelled')) NOT VALID;
    ELSIF cur_def NOT LIKE '%voicemail%' THEN
      ALTER TABLE "phone_calls" DROP CONSTRAINT "phone_calls_status_check";
      ALTER TABLE "phone_calls" ADD CONSTRAINT "phone_calls_status_check"
        CHECK (status IN ('ringing','active','voicemail','ended','declined','missed','cancelled')) NOT VALID;
    END IF;
  END $$;`,
  // Force-end audit: structured actor column so the staff member who terminated a call is
  // queryable without parsing `ended_reason`. Same rogue-staff threat model as `phone_taps`.
  `ALTER TABLE "phone_calls" ADD COLUMN IF NOT EXISTS "force_ended_by_id" uuid REFERENCES "players"("id");`,
  // Only re-issue the ALTER COLUMN TYPE on legacy deployments where the column is not yet
  // varchar(80). Skipping the AccessExclusiveLock on healthy schemas keeps re-runs cheap.
  // The USING cast mirrors the parallel `error`-column ALTER below: if a legacy row already
  // exceeds 80 chars the implicit cast would abort the migration, so truncate explicitly.
  `DO $$ BEGIN
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name = 'phone_calls'
        AND column_name = 'ended_reason'
        AND (character_maximum_length IS NULL OR character_maximum_length <> 80)
    ) THEN
      ALTER TABLE "phone_calls" ALTER COLUMN "ended_reason" TYPE varchar(80) USING substr("ended_reason", 1, 80);
    END IF;
  END $$;`,
  `DROP INDEX IF EXISTS "phone_calls_one_open_caller";`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "phone_calls_one_open_caller"
    ON "phone_calls" ("caller_player_id")
    WHERE status IN ('ringing','active','voicemail');`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "phone_calls_one_open_recipient"
    ON "phone_calls" ("recipient_player_id")
    WHERE status IN ('ringing','active');`,
  `CREATE INDEX IF NOT EXISTS "phone_calls_caller_history_idx"
    ON "phone_calls" ("caller_player_id", "started_at");`,
  `CREATE INDEX IF NOT EXISTS "phone_calls_recipient_history_idx"
    ON "phone_calls" ("recipient_player_id", "started_at");`,
  // Index for sweepStrandedActiveCalls — only scans active rows, ordered by started_at.
  `CREATE INDEX IF NOT EXISTS "phone_calls_active_started_idx"
    ON "phone_calls" ("started_at")
    WHERE status = 'active';`,
  // Index for the ring-timeout worker — only scans ringing rows, ordered by ring_expires_at.
  `CREATE INDEX IF NOT EXISTS "phone_calls_ring_timeout_idx"
    ON "phone_calls" ("ring_expires_at")
    WHERE status = 'ringing';`,

  // === phone_messages ===
  `CREATE TABLE IF NOT EXISTS "phone_messages" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "call_id" uuid NOT NULL REFERENCES "phone_calls"("id") ON DELETE CASCADE,
    "sender_player_id" uuid NOT NULL REFERENCES "players"("id"),
    "content" text NOT NULL,
    "sender_discord_message_id" varchar(20),
    "recipient_discord_message_id" varchar(20),
    "staff_mirror_message_id" varchar(20),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "sequence_no" bigserial NOT NULL
  );`,
  // `sequence_no` is the monotonic transcript tiebreaker — `created_at` alone is
  // millisecond-resolution and ties sort non-deterministically. For legacy deployments that
  // predate this column, add it as bigserial: Postgres creates the owned sequence and
  // backfills every existing row with a strictly-increasing value. Idempotent — skipped if
  // the column already exists. NOTE: `ADD COLUMN ... bigserial NOT NULL` rewrites the whole
  // table under an AccessExclusiveLock (every row gets a `nextval`); it won't fail, but it
  // is not an online change. Acceptable here — `phone_messages` is a small append-only
  // transcript table and this only runs once per legacy deployment.
  `DO $$ BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name = 'phone_messages' AND column_name = 'sequence_no'
    ) THEN
      ALTER TABLE "phone_messages" ADD COLUMN "sequence_no" bigserial NOT NULL;
    END IF;
  END $$;`,
  `CREATE INDEX IF NOT EXISTS "phone_messages_call_idx"
    ON "phone_messages" ("call_id", "created_at");`,
  `CREATE INDEX IF NOT EXISTS "phone_messages_pending_delivery_idx"
    ON "phone_messages" ("created_at")
    WHERE recipient_discord_message_id IS NULL;`,

  // === phone_threads ===
  `CREATE TABLE IF NOT EXISTS "phone_threads" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "player_a_id" uuid NOT NULL REFERENCES "players"("id"),
    "player_b_id" uuid NOT NULL REFERENCES "players"("id"),
    "discord_thread_id" varchar(20) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now()
  );`,
  `DO $$ BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'phone_threads_ordered_pair'
        AND conrelid = '"phone_threads"'::regclass
    )
    THEN ALTER TABLE "phone_threads" ADD CONSTRAINT "phone_threads_ordered_pair"
      CHECK (player_a_id < player_b_id) NOT VALID;
    END IF;
  END $$;`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "phone_threads_pair_unique"
    ON "phone_threads" ("player_a_id", "player_b_id");`,
  // One DB row per Discord thread id. Backstops the find/create/persist race: if two relays
  // both create a Discord thread for the same pair, the second INSERT trips this unique index
  // and the loser deletes its just-created orphan thread.
  `CREATE UNIQUE INDEX IF NOT EXISTS "phone_threads_discord_thread_unique"
    ON "phone_threads" ("discord_thread_id");`,

  // === phone_taps ===
  `CREATE TABLE IF NOT EXISTS "phone_taps" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "target_number_id" uuid NOT NULL REFERENCES "phone_numbers"("id") ON DELETE RESTRICT,
    "created_by_id" uuid NOT NULL REFERENCES "players"("id"),
    "mirror_channel_id" varchar(20),
    "mirror_discord_user_id" varchar(20),
    "reason" text,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "revoked_at" timestamptz,
    "revoked_by_id" uuid REFERENCES "players"("id")
  );`,
  // Rename mirror_user_id → mirror_discord_user_id on phone_taps, idempotent. Handles three
  // states: (a) only old column → rename; (b) both columns → copy then drop old; (c) only new
  // column → no-op.
  `DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_taps' AND column_name = 'mirror_user_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_taps' AND column_name = 'mirror_discord_user_id')
    THEN ALTER TABLE "phone_taps" RENAME COLUMN "mirror_user_id" TO "mirror_discord_user_id";
    ELSIF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_taps' AND column_name = 'mirror_user_id')
       AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_taps' AND column_name = 'mirror_discord_user_id')
    THEN
      UPDATE "phone_taps" SET "mirror_discord_user_id" = "mirror_user_id" WHERE "mirror_discord_user_id" IS NULL AND "mirror_user_id" IS NOT NULL;
      ALTER TABLE "phone_taps" DROP COLUMN "mirror_user_id";
    END IF;
  END $$;`,
  `CREATE INDEX IF NOT EXISTS "phone_taps_active_number_idx"
    ON "phone_taps" ("target_number_id")
    WHERE is_active = true;`,
  // The duplicate-tap cleanup below writes audit rows, so ensure the audit table + columns
  // exist before retiring legacy rows. The canonical audit section later repeats these
  // idempotent guards and adds constraints/indexes/triggers.
  `CREATE TABLE IF NOT EXISTS "phone_tap_audit_log" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "tap_id" uuid NOT NULL REFERENCES "phone_taps"("id") ON DELETE RESTRICT,
    "actor_id" uuid NOT NULL REFERENCES "players"("id"),
    "action" varchar(32) NOT NULL,
    "target_number_id" uuid,
    "target_number_normalized" varchar(32),
    "mirror_channel_id" varchar(20),
    "mirror_discord_user_id" varchar(20),
    "notes" text,
    "created_at" timestamptz NOT NULL DEFAULT now()
  );`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "target_number_id" uuid;`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "target_number_normalized" varchar(32);`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "mirror_channel_id" varchar(20);`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "mirror_discord_user_id" varchar(20);`,
  `INSERT INTO "phone_tap_audit_log" (
      "tap_id",
      "actor_id",
      "action",
      "target_number_id",
      "target_number_normalized",
      "mirror_channel_id",
      "mirror_discord_user_id",
      "notes"
    )
    SELECT
      t."id",
      t."created_by_id",
      'orphaned_target_deactivated',
      t."target_number_id",
      n."number_normalized",
      t."mirror_channel_id",
      t."mirror_discord_user_id",
      'Duplicate active tap auto-revoked by migration'
    FROM "phone_taps" t
    LEFT JOIN "phone_numbers" n ON n."id" = t."target_number_id"
    WHERE t."is_active" = true
      AND EXISTS (
        SELECT 1 FROM "phone_taps" newer
        WHERE newer."target_number_id" = t."target_number_id"
          AND newer."is_active" = true
          AND (newer."created_at" > t."created_at"
               OR (newer."created_at" = t."created_at" AND newer."id" > t."id"))
      )
      AND NOT EXISTS (
        SELECT 1 FROM "phone_tap_audit_log" existing
        WHERE existing."tap_id" = t."id"
          AND existing."action" = 'orphaned_target_deactivated'
          AND existing."notes" = 'Duplicate active tap auto-revoked by migration'
      );`,
  // Before adding the active-target unique index, retire any pre-existing duplicate active
  // taps on the same number — keep the newest, deactivate the rest — so `CREATE UNIQUE INDEX`
  // does not abort on legacy data. Skipped (no rows updated) once the invariant holds, so
  // re-runs are no-ops.
  `UPDATE "phone_taps" t
     SET "is_active" = false,
         "revoked_at" = COALESCE(t."revoked_at", now())
   WHERE t."is_active" = true
     AND EXISTS (
       SELECT 1 FROM "phone_taps" newer
       WHERE newer."target_number_id" = t."target_number_id"
         AND newer."is_active" = true
         AND (newer."created_at" > t."created_at"
              OR (newer."created_at" = t."created_at" AND newer."id" > t."id"))
     );`,
  // At most one active tap per target number. Without this, two staff tapping the same number
  // produce two active rows and every message mirrors once per duplicate tap.
  `CREATE UNIQUE INDEX IF NOT EXISTS "phone_taps_active_target_unique"
    ON "phone_taps" ("target_number_id")
    WHERE is_active = true;`,
  // Drop redundant index — the original `phone_taps_consecutive_failure_idx` on (id) WHERE
  // is_active=true duplicated the primary key for the only access pattern that reached it.
  // The actual circuit-breaker query reads from `phone_message_tap_deliveries` and is served
  // by `phone_message_tap_deliveries_tap_created_idx`.
  `DROP INDEX IF EXISTS "phone_taps_consecutive_failure_idx";`,

  // === phone_tap_audit_log ===
  `CREATE TABLE IF NOT EXISTS "phone_tap_audit_log" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "tap_id" uuid NOT NULL REFERENCES "phone_taps"("id") ON DELETE RESTRICT,
    "actor_id" uuid NOT NULL REFERENCES "players"("id"),
    "action" varchar(32) NOT NULL,
    "target_number_id" uuid,
    "target_number_normalized" varchar(32),
    "mirror_channel_id" varchar(20),
    "mirror_discord_user_id" varchar(20),
    "notes" text,
    "created_at" timestamptz NOT NULL DEFAULT now()
  );`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "target_number_id" uuid;`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "target_number_normalized" varchar(32);`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "mirror_channel_id" varchar(20);`,
  `ALTER TABLE "phone_tap_audit_log" ADD COLUMN IF NOT EXISTS "mirror_discord_user_id" varchar(20);`,
  // Parallel rename block for the audit table — same three states as phone_taps.
  `DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_tap_audit_log' AND column_name = 'mirror_user_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_tap_audit_log' AND column_name = 'mirror_discord_user_id')
    THEN ALTER TABLE "phone_tap_audit_log" RENAME COLUMN "mirror_user_id" TO "mirror_discord_user_id";
    ELSIF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_tap_audit_log' AND column_name = 'mirror_user_id')
       AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'phone_tap_audit_log' AND column_name = 'mirror_discord_user_id')
    THEN
      UPDATE "phone_tap_audit_log" SET "mirror_discord_user_id" = "mirror_user_id" WHERE "mirror_discord_user_id" IS NULL AND "mirror_user_id" IS NOT NULL;
      ALTER TABLE "phone_tap_audit_log" DROP COLUMN "mirror_user_id";
    END IF;
  END $$;`,
  // Action enum includes `number_deactivated` — written when deactivating a number
  // auto-revokes its taps. Legacy deployments may already carry the constraint with the
  // narrower 3-value enum; drop and re-add (NOT VALID) so the new value is permitted. The
  // re-add is conditional on the current definition lacking `number_deactivated`, so a
  // healthy schema is a true no-op.
  `DO $$
  DECLARE
    cur_def text;
  BEGIN
    SELECT pg_get_constraintdef(c.oid) INTO cur_def
    FROM pg_constraint c
    WHERE c.conname = 'phone_tap_audit_log_action_check'
      AND c.conrelid = '"phone_tap_audit_log"'::regclass;
    IF cur_def IS NULL THEN
      ALTER TABLE "phone_tap_audit_log" ADD CONSTRAINT "phone_tap_audit_log_action_check"
        CHECK (action IN ('created','revoked','orphaned_target_deactivated','number_deactivated')) NOT VALID;
    ELSIF cur_def NOT LIKE '%number_deactivated%' THEN
      ALTER TABLE "phone_tap_audit_log" DROP CONSTRAINT "phone_tap_audit_log_action_check";
      ALTER TABLE "phone_tap_audit_log" ADD CONSTRAINT "phone_tap_audit_log_action_check"
        CHECK (action IN ('created','revoked','orphaned_target_deactivated','number_deactivated')) NOT VALID;
    END IF;
  END $$;`,
  // Staff "history of this tap" inspections read every audit row for one tap in time order.
  `CREATE INDEX IF NOT EXISTS "phone_tap_audit_log_tap_created_idx"
    ON "phone_tap_audit_log" ("tap_id", "created_at");`,
  // Defense-in-depth for the rogue-staff threat model: the audit log is append-only. A
  // BEFORE UPDATE OR DELETE trigger raises so even a compromised app role (or a stray
  // service-layer bug) cannot rewrite or erase audit history. Trigger approach chosen over
  // REVOKE because it needs no knowledge of the deployment's app role name. Idempotent:
  // CREATE OR REPLACE the function, drop+recreate the trigger.
  `CREATE OR REPLACE FUNCTION "phone_tap_audit_log_immutable"()
   RETURNS trigger AS $$
   BEGIN
     RAISE EXCEPTION 'phone_tap_audit_log is append-only: % is not permitted', TG_OP
       USING ERRCODE = 'restrict_violation';
   END;
   $$ LANGUAGE plpgsql;`,
  `DROP TRIGGER IF EXISTS "phone_tap_audit_log_no_mutate" ON "phone_tap_audit_log";`,
  `CREATE TRIGGER "phone_tap_audit_log_no_mutate"
     BEFORE UPDATE OR DELETE ON "phone_tap_audit_log"
     FOR EACH ROW EXECUTE FUNCTION "phone_tap_audit_log_immutable"();`,

  // === phone_message_tap_deliveries ===
  // `error` is bounded to varchar(500) — Discord stack traces can run multiple KB and we don't
  // need full traces for audit triage; the message is enough.
  `CREATE TABLE IF NOT EXISTS "phone_message_tap_deliveries" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "message_id" uuid NOT NULL REFERENCES "phone_messages"("id") ON DELETE CASCADE,
    "tap_id" uuid NOT NULL REFERENCES "phone_taps"("id") ON DELETE RESTRICT,
    "mirror_message_id" varchar(20),
    "delivered_at" timestamptz,
    "error" varchar(500),
    "created_at" timestamptz NOT NULL DEFAULT now()
  );`,
  `ALTER TABLE "phone_message_tap_deliveries" ADD COLUMN IF NOT EXISTS "created_at" timestamptz NOT NULL DEFAULT now();`,
  // For prior deployments where `error` was `text` (or a larger varchar), narrow it. Skip if
  // the column is already varchar(500) so a re-run doesn't take an AccessExclusiveLock for
  // a no-op. The USING expression truncates safely if any row exceeds 500 chars.
  `DO $$ BEGIN
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name = 'phone_message_tap_deliveries'
        AND column_name = 'error'
        AND (character_maximum_length IS NULL OR character_maximum_length <> 500)
    ) THEN
      ALTER TABLE "phone_message_tap_deliveries" ALTER COLUMN "error" TYPE varchar(500) USING substr("error", 1, 500);
    END IF;
  END $$;`,
  `CREATE INDEX IF NOT EXISTS "phone_message_tap_deliveries_tap_created_idx"
    ON "phone_message_tap_deliveries" ("tap_id", "created_at" DESC);`,
  // Supports the worker sweep for crash-stranded placeholder deliveries — rows still
  // `delivered_at IS NULL AND error IS NULL` past the stale cutoff. Partial so only the
  // small in-flight set is indexed; completed rows are excluded.
  `CREATE INDEX IF NOT EXISTS "phone_message_tap_deliveries_pending_idx"
    ON "phone_message_tap_deliveries" ("created_at")
    WHERE delivered_at IS NULL AND error IS NULL;`,
];

const validateStatements: string[] = [
  `ALTER TABLE "phone_numbers" VALIDATE CONSTRAINT "phone_numbers_normalized_shape";`,
  `ALTER TABLE "phone_calls" VALIDATE CONSTRAINT "phone_calls_status_check";`,
  `ALTER TABLE "phone_threads" VALIDATE CONSTRAINT "phone_threads_ordered_pair";`,
  `ALTER TABLE "phone_tap_audit_log" VALIDATE CONSTRAINT "phone_tap_audit_log_action_check";`,
];

const rollbackStatements: string[] = [
  // Reverse FK order: deliveries → audit_log → taps → threads → messages → calls → numbers.
  `DROP TABLE IF EXISTS "phone_message_tap_deliveries" CASCADE;`,
  `DROP TABLE IF EXISTS "phone_tap_audit_log" CASCADE;`,
  `DROP FUNCTION IF EXISTS "phone_tap_audit_log_immutable"();`,
  `DROP TABLE IF EXISTS "phone_taps" CASCADE;`,
  `DROP TABLE IF EXISTS "phone_threads" CASCADE;`,
  `DROP TABLE IF EXISTS "phone_messages" CASCADE;`,
  `DROP TABLE IF EXISTS "phone_calls" CASCADE;`,
  `DROP TABLE IF EXISTS "phone_numbers" CASCADE;`,
];

async function main() {
  const toRun = validate ? validateStatements : rollback ? rollbackStatements : statements;

  if (dryRun) {
    console.log(validate ? '--- DRY RUN VALIDATE ---' : rollback ? '--- DRY RUN ROLLBACK ---' : '--- DRY RUN, would execute ---');
    for (const stmt of toRun) {
      console.log(stmt);
    }
    return;
  }

  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error('DATABASE_URL not set');
    process.exit(1);
  }

  if (rollback && !process.argv.includes('--confirm')) {
    console.error('Rollback requires --confirm to proceed. This DROPs every phone_* table CASCADE.');
    process.exit(1);
  }

  const sql = postgres(url, { max: 1 });
  try {
    // Wrap the whole migration in a single transaction so a partial failure rolls back. Every
    // statement is DDL on its own table or a DO $$ block; PG supports transactional DDL.
    await sql.begin(async (tx) => {
      for (const stmt of toRun) {
        console.log('Applying:', stmt.split('\n')[0]);
        await tx.unsafe(stmt);
      }
    });
    console.log(validate
      ? `Done. Validated ${toRun.length} phone constraints.`
      : rollback
      ? `Done. Dropped ${toRun.length} phone tables.`
      : `Done. Applied ${toRun.length} statements. Phone registry tables present.`);
  } finally {
    await sql.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
